# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('probability', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('scanned_on', models.DateTimeField()),
            ],
        ),
    ]
